[mypy]
python_version = 3.11
check_untyped_defs = True
explicit_package_bases = True
follow_imports = silent
ignore_missing_imports = True
namespace_packages = True
no_implicit_optional = True
pretty = True
show_error_codes = True
warn_unused_configs = True
exclude = (?x)(
    ^.git/
    | ^.mypy_cache/
    | ^.ruff_cache/
    | ^.venv/
    | /node_modules/
    | /dist/
  )
