/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List synthetic missions */
        get: operations["list_synthetic_missions_sources_synthetic_missions_get"];
        put?: never;
        /** Create a synthetic mission */
        post: operations["create_synthetic_mission_sources_synthetic_missions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get synthetic mission status */
        get: operations["get_synthetic_mission_status_sources_synthetic_missions__mission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a synthetic mission */
        post: operations["start_synthetic_mission_sources_synthetic_missions__mission_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause a synthetic mission */
        post: operations["pause_synthetic_mission_sources_synthetic_missions__mission_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a synthetic mission */
        post: operations["resume_synthetic_mission_sources_synthetic_missions__mission_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a synthetic mission */
        post: operations["stop_synthetic_mission_sources_synthetic_missions__mission_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a command to a synthetic mission */
        post: operations["submit_synthetic_mission_command_sources_synthetic_missions__mission_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current synthetic telemetry sample */
        get: operations["get_current_synthetic_sample_sources_synthetic_missions__mission_id__sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}/sample/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance mission time and get next synthetic telemetry sample */
        post: operations["get_next_synthetic_sample_sources_synthetic_missions__mission_id__sample_next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/synthetic/missions/{mission_id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate a batch of synthetic telemetry samples */
        get: operations["get_synthetic_sample_batch_sources_synthetic_missions__mission_id__samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List uploaded snapshots */
        get: operations["list_snapshots_sources_snapshots_get"];
        put?: never;
        /** Upload a telemetry snapshot */
        post: operations["create_snapshot_sources_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get snapshot status */
        get: operations["get_snapshot_status_sources_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/snapshots/{snapshot_id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read snapshot samples */
        get: operations["get_snapshot_samples_sources_snapshots__snapshot_id__samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/snapshots/{snapshot_id}/send-once/udp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a snapshot once through MAVLink-over-UDP */
        post: operations["send_snapshot_once_udp_sources_snapshots__snapshot_id__send_once_udp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List external telemetry sources */
        get: operations["list_external_sources_sources_external_get"];
        put?: never;
        /** Register an external telemetry source */
        post: operations["create_external_source_sources_external_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/external/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get external source status */
        get: operations["get_external_source_status_sources_external__source_id__get"];
        put?: never;
        post?: never;
        /** Delete external UDP telemetry source */
        delete: operations["delete_external_source_sources_external__source_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/external/{source_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start external UDP telemetry ingestion */
        post: operations["start_external_source_sources_external__source_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/external/{source_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop external UDP telemetry ingestion */
        post: operations["stop_external_source_sources_external__source_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List telemetry stream capabilities */
        get: operations["list_stream_capabilities_streams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/synthetic/missions/{mission_id}/udp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start continuous MAVLink-over-UDP publication */
        post: operations["start_synthetic_udp_stream_streams_synthetic_missions__mission_id__udp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/udp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List UDP publication streams */
        get: operations["list_udp_streams_streams_udp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/udp/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get UDP publication stream status */
        get: operations["get_udp_stream_status_streams_udp__stream_id__get"];
        put?: never;
        post?: never;
        /** Stop UDP publication stream */
        delete: operations["stop_udp_stream_streams_udp__stream_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/udp/{stream_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview recent synthetic UDP stream samples */
        get: operations["get_udp_stream_preview_streams_udp__stream_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/snapshots/{snapshot_id}/udp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay a snapshot through MAVLink-over-UDP */
        post: operations["start_snapshot_udp_stream_streams_snapshots__snapshot_id__udp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/snapshots/udp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List snapshot UDP streams */
        get: operations["list_snapshot_udp_streams_streams_snapshots_udp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/snapshots/udp/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get snapshot UDP stream status */
        get: operations["get_snapshot_udp_stream_status_streams_snapshots_udp__stream_id__get"];
        put?: never;
        post?: never;
        /** Stop snapshot UDP stream */
        delete: operations["stop_snapshot_udp_stream_streams_snapshots_udp__stream_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/snapshots/udp/{stream_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview recent snapshot UDP stream samples */
        get: operations["get_snapshot_udp_stream_preview_streams_snapshots_udp__stream_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Translations */
        get: operations["translations_translations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatteryProfileRequest */
        BatteryProfileRequest: {
            /**
             * Takeoff Percent Per Sec
             * @default 0.025
             */
            takeoff_percent_per_sec: number;
            /**
             * Waypoint Percent Per Sec
             * @default 0.015
             */
            waypoint_percent_per_sec: number;
            /**
             * Turn Percent Per Sec
             * @default 0.01
             */
            turn_percent_per_sec: number;
            /**
             * Hover Percent Per Sec
             * @default 0.012
             */
            hover_percent_per_sec: number;
            /**
             * Return Home Percent Per Sec
             * @default 0.015
             */
            return_home_percent_per_sec: number;
            /**
             * Landing Percent Per Sec
             * @default 0.01
             */
            landing_percent_per_sec: number;
        };
        /**
         * CommandType
         * @description Commands accepted by the synthetic mission runtime.
         * @enum {string}
         */
        CommandType: "inject_anomaly" | "set_parameter" | "pause" | "resume" | "stop";
        /** ExternalSourceCreateRequest */
        ExternalSourceCreateRequest: {
            /** Name */
            name: string;
            /**
             * Address
             * @default 0.0.0.0
             */
            address: string;
            /**
             * Port
             * @default 14540
             */
            port: number;
            /** @default udp */
            protocol: components["schemas"]["ExternalTransportProtocol"];
            /**
             * Forward Enabled
             * @default true
             */
            forward_enabled: boolean;
            /**
             * Forward Host
             * @default analysis-service
             */
            forward_host: string;
            /**
             * Forward Port
             * @default 14560
             */
            forward_port: number;
        };
        /** ExternalSourceCreatedResponse */
        ExternalSourceCreatedResponse: {
            /** Source Id */
            source_id: string;
            status: components["schemas"]["ExternalSourceStatusResponse"];
        };
        /** ExternalSourceDeletedResponse */
        ExternalSourceDeletedResponse: {
            /** Source Id */
            source_id: string;
            /** Deleted */
            deleted: boolean;
        };
        /** ExternalSourceListItemResponse */
        ExternalSourceListItemResponse: {
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Port */
            port: number;
            /** Protocol */
            protocol: string;
            /** Forward Enabled */
            forward_enabled: boolean;
            /** Forward Host */
            forward_host: string;
            /** Forward Port */
            forward_port: number;
            /** Is Active */
            is_active: boolean;
            /** Received Packets */
            received_packets: number;
            /** Forwarded Packets */
            forwarded_packets: number;
        };
        /** ExternalSourceStatusResponse */
        ExternalSourceStatusResponse: {
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Port */
            port: number;
            /** Protocol */
            protocol: string;
            /** Forward Enabled */
            forward_enabled: boolean;
            /** Forward Host */
            forward_host: string;
            /** Forward Port */
            forward_port: number;
            /** Is Active */
            is_active: boolean;
            /** Received Packets */
            received_packets: number;
            /** Received Bytes */
            received_bytes: number;
            /** Forwarded Packets */
            forwarded_packets: number;
            /** Last Received At */
            last_received_at?: string | null;
            /** Last Forwarded At */
            last_forwarded_at?: string | null;
            /** Last Remote Address */
            last_remote_address?: string | null;
            /** Last Remote Port */
            last_remote_port?: number | null;
            /** Last Payload Size */
            last_payload_size?: number | null;
            /** Last Payload Preview Hex */
            last_payload_preview_hex?: string | null;
            /** Last Payload Preview Ascii */
            last_payload_preview_ascii?: string | null;
            /** Last Payload Preview Truncated */
            last_payload_preview_truncated?: boolean;
            /** Last Error */
            last_error?: string | null;
            /** Last Forward Error */
            last_forward_error?: string | null;
        };
        /**
         * ExternalTransportProtocol
         * @description Supported external source transport protocols.
         * @enum {string}
         */
        ExternalTransportProtocol: "udp";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LanguageResponse */
        LanguageResponse: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** MissionCommandRequest */
        MissionCommandRequest: {
            command: components["schemas"]["CommandType"];
            /** Type */
            type?: string | null;
            /** Start After Sec */
            start_after_sec?: number | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Intensity */
            intensity?: number | null;
            /** Name */
            name?: string | null;
            /** Value */
            value?: unknown;
        };
        /** MissionCreatedResponse */
        MissionCreatedResponse: {
            /** Mission Id */
            mission_id: string;
            status: components["schemas"]["MissionStatusResponse"];
        };
        /** MissionListItemResponse */
        MissionListItemResponse: {
            /** Mission Id */
            mission_id: string;
            /** Name */
            name: string;
            /** Frequency Hz */
            frequency_hz: number;
            /** Is Running */
            is_running: boolean;
            /** Is Completed */
            is_completed: boolean;
        };
        /** MissionScriptRequest */
        MissionScriptRequest: {
            /** Name */
            name: string;
            /** Frequency Hz */
            frequency_hz: number;
            home: components["schemas"]["ScriptHomeRequest"];
            /** Steps */
            steps: components["schemas"]["ScriptStepRequest"][];
            /**
             * Drone Id
             * @default uav-001
             */
            drone_id: string;
            motion_profile?: components["schemas"]["MotionProfileRequest"];
            noise_profile?: components["schemas"]["NoiseProfileRequest"];
            battery_profile?: components["schemas"]["BatteryProfileRequest"];
        };
        /** MissionStatusResponse */
        MissionStatusResponse: {
            /** Mission Id */
            mission_id: string;
            /** Name */
            name: string;
            /** Frequency Hz */
            frequency_hz: number;
            /** Elapsed Sec */
            elapsed_sec: number;
            /** Total Duration Sec */
            total_duration_sec: number;
            /** Active Phase Index */
            active_phase_index: number;
            /** Is Running */
            is_running: boolean;
            /** Is Completed */
            is_completed: boolean;
            /** Scheduled Anomalies Count */
            scheduled_anomalies_count: number;
        };
        /** MotionProfileRequest */
        MotionProfileRequest: {
            /**
             * Horizontal Acceleration M S2
             * @default 2
             */
            horizontal_acceleration_m_s2: number;
            /**
             * Default Climb Rate M S
             * @default 3
             */
            default_climb_rate_m_s: number;
            /**
             * Default Descent Rate M S
             * @default 2
             */
            default_descent_rate_m_s: number;
            /**
             * Default Yaw Rate Deg S
             * @default 45
             */
            default_yaw_rate_deg_s: number;
            /**
             * Default Return Speed M S
             * @default 8
             */
            default_return_speed_m_s: number;
        };
        /** NoiseProfileRequest */
        NoiseProfileRequest: {
            /** Random Seed */
            random_seed?: number | null;
            /**
             * Gps Position Std M
             * @default 0
             */
            gps_position_std_m: number;
            /**
             * Altitude Std M
             * @default 0
             */
            altitude_std_m: number;
            /**
             * Speed Std M S
             * @default 0
             */
            speed_std_m_s: number;
            /**
             * Heading Std Deg
             * @default 0
             */
            heading_std_deg: number;
            /**
             * Battery Std Percent
             * @default 0
             */
            battery_std_percent: number;
        };
        /** ScriptHomeRequest */
        ScriptHomeRequest: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Altitude
             * @default 0
             */
            altitude: number;
            /**
             * Heading Deg
             * @default 0
             */
            heading_deg: number;
            /**
             * Battery
             * @default 100
             */
            battery: number;
        };
        /** ScriptStepRequest */
        ScriptStepRequest: {
            type: components["schemas"]["ScriptStepType"];
            /** Target Altitude */
            target_altitude?: number | null;
            /** Distance M */
            distance_m?: number | null;
            /** Speed M S */
            speed_m_s?: number | null;
            direction?: components["schemas"]["TurnDirection"] | null;
            /** Angle Deg */
            angle_deg?: number | null;
            /** Duration Sec */
            duration_sec?: number | null;
        };
        /**
         * ScriptStepType
         * @description Supported mission script step types.
         * @enum {string}
         */
        ScriptStepType: "takeoff" | "move_forward" | "turn" | "hover" | "return_home" | "landing";
        /** SnapshotCreateRequest */
        SnapshotCreateRequest: {
            /** Name */
            name: string;
            /** Samples */
            samples: components["schemas"]["SnapshotSampleRequest"][];
            /**
             * Interval Seconds
             * @default 1
             */
            interval_seconds: number;
            /**
             * Repeat
             * @default false
             */
            repeat: boolean;
        };
        /** SnapshotCreatedResponse */
        SnapshotCreatedResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            status: components["schemas"]["SnapshotStatusResponse"];
        };
        /** SnapshotListItemResponse */
        SnapshotListItemResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Name */
            name: string;
            /** Samples Count */
            samples_count: number;
        };
        /** SnapshotSampleRequest */
        SnapshotSampleRequest: {
            /** Timestamp */
            timestamp: string;
            /** Drone Id */
            drone_id: string;
            /** Latitude Deg */
            latitude_deg: number;
            /** Longitude Deg */
            longitude_deg: number;
            /** Altitude M */
            altitude_m: number;
            /** Battery Percent */
            battery_percent: number;
            /** Satellites */
            satellites: number;
            /** Ground Speed M S */
            ground_speed_m_s?: number | null;
            /** Vertical Speed M S */
            vertical_speed_m_s?: number | null;
            /** Heading Deg */
            heading_deg?: number | null;
            /** Relative Altitude M */
            relative_altitude_m?: number | null;
            /** Velocity X M S */
            velocity_x_m_s?: number | null;
            /** Velocity Y M S */
            velocity_y_m_s?: number | null;
            /** Velocity Z M S */
            velocity_z_m_s?: number | null;
            /** Roll Rad */
            roll_rad?: number | null;
            /** Pitch Rad */
            pitch_rad?: number | null;
            /** Yaw Rad */
            yaw_rad?: number | null;
            /** Roll Rate Rad S */
            roll_rate_rad_s?: number | null;
            /** Pitch Rate Rad S */
            pitch_rate_rad_s?: number | null;
            /** Yaw Rate Rad S */
            yaw_rate_rad_s?: number | null;
            /** Satellites Visible */
            satellites_visible?: number | null;
            /** Gps Fix Type */
            gps_fix_type?: number | null;
            /** Gps Eph */
            gps_eph?: number | null;
            /** Gps Epv */
            gps_epv?: number | null;
            /** Battery Voltage V */
            battery_voltage_v?: number | null;
            /** Battery Current A */
            battery_current_a?: number | null;
            /** System Status */
            system_status?: string | null;
            /** Flight Mode */
            flight_mode?: string | null;
            /** Armed */
            armed?: boolean | null;
            /** Sensor Health Flags */
            sensor_health_flags?: number | null;
        };
        /** SnapshotSamplesResponse */
        SnapshotSamplesResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Samples */
            samples: components["schemas"]["TelemetrySampleResponse"][];
        };
        /** SnapshotSendOnceResponse */
        SnapshotSendOnceResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Host */
            host: string;
            /** Port */
            port: number;
            /** Samples Sent */
            samples_sent: number;
            /** Frames Sent */
            frames_sent: number;
        };
        /** SnapshotStatusResponse */
        SnapshotStatusResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Name */
            name: string;
            /** Samples Count */
            samples_count: number;
            /** Interval Seconds */
            interval_seconds: number;
            /** Repeat */
            repeat: boolean;
        };
        /** SnapshotUdpStreamStatusResponse */
        SnapshotUdpStreamStatusResponse: {
            /** Stream Id */
            stream_id: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Host */
            host: string;
            /** Port */
            port: number;
            /** Frequency Hz */
            frequency_hz: number;
            /** Repeat */
            repeat: boolean;
            /** Is Active */
            is_active: boolean;
            /** Samples Sent */
            samples_sent: number;
            /** Frames Sent */
            frames_sent: number;
        };
        /** StreamPreviewResponse */
        StreamPreviewResponse: {
            /** Stream Id */
            stream_id: string;
            /** Samples */
            samples: components["schemas"]["TelemetrySampleResponse"][];
        };
        /** TelemetrySampleResponse */
        TelemetrySampleResponse: {
            /** Timestamp */
            timestamp: string;
            /** Drone Id */
            drone_id: string;
            /** Latitude Deg */
            latitude_deg: number;
            /** Longitude Deg */
            longitude_deg: number;
            /** Altitude M */
            altitude_m: number;
            /** Battery Percent */
            battery_percent: number;
            /** Satellites */
            satellites: number;
            /** Ground Speed M S */
            ground_speed_m_s?: number | null;
            /** Vertical Speed M S */
            vertical_speed_m_s?: number | null;
            /** Heading Deg */
            heading_deg?: number | null;
            /** Relative Altitude M */
            relative_altitude_m?: number | null;
            /** Velocity X M S */
            velocity_x_m_s?: number | null;
            /** Velocity Y M S */
            velocity_y_m_s?: number | null;
            /** Velocity Z M S */
            velocity_z_m_s?: number | null;
            /** Roll Rad */
            roll_rad?: number | null;
            /** Pitch Rad */
            pitch_rad?: number | null;
            /** Yaw Rad */
            yaw_rad?: number | null;
            /** Roll Rate Rad S */
            roll_rate_rad_s?: number | null;
            /** Pitch Rate Rad S */
            pitch_rate_rad_s?: number | null;
            /** Yaw Rate Rad S */
            yaw_rate_rad_s?: number | null;
            /** Satellites Visible */
            satellites_visible?: number | null;
            /** Gps Fix Type */
            gps_fix_type?: number | null;
            /** Gps Eph */
            gps_eph?: number | null;
            /** Gps Epv */
            gps_epv?: number | null;
            /** Battery Voltage V */
            battery_voltage_v?: number | null;
            /** Battery Current A */
            battery_current_a?: number | null;
            /** System Status */
            system_status?: string | null;
            /** Flight Mode */
            flight_mode?: string | null;
            /** Armed */
            armed?: boolean | null;
            /** Sensor Health Flags */
            sensor_health_flags?: number | null;
        };
        /** TickRequest */
        TickRequest: {
            /** Delta Sec */
            delta_sec?: number | null;
        };
        /** TranslationsResponse */
        TranslationsResponse: {
            /** Default Language */
            default_language: string;
            /** Languages */
            languages: components["schemas"]["LanguageResponse"][];
            /** Messages */
            messages: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /**
         * TurnDirection
         * @description Supported turn directions.
         * @enum {string}
         */
        TurnDirection: "left" | "right";
        /** UdpStreamRequest */
        UdpStreamRequest: {
            /**
             * Host
             * @default analysis-service
             */
            host: string;
            /**
             * Port
             * @default 14560
             */
            port: number;
            /** Frequency Hz */
            frequency_hz?: number | null;
            /** Repeat */
            repeat?: boolean | null;
        };
        /** UdpStreamStatusResponse */
        UdpStreamStatusResponse: {
            /** Stream Id */
            stream_id: string;
            /** Mission Id */
            mission_id: string;
            /** Host */
            host: string;
            /** Port */
            port: number;
            /** Frequency Hz */
            frequency_hz: number;
            /** Is Active */
            is_active: boolean;
            /** Sent Count */
            sent_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_synthetic_missions_sources_synthetic_missions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionListItemResponse"][];
                };
            };
        };
    };
    create_synthetic_mission_sources_synthetic_missions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionScriptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_synthetic_mission_status_sources_synthetic_missions__mission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_synthetic_mission_sources_synthetic_missions__mission_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_synthetic_mission_sources_synthetic_missions__mission_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_synthetic_mission_sources_synthetic_missions__mission_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_synthetic_mission_sources_synthetic_missions__mission_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_synthetic_mission_command_sources_synthetic_missions__mission_id__commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_synthetic_sample_sources_synthetic_missions__mission_id__sample_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetrySampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_synthetic_sample_sources_synthetic_missions__mission_id__sample_next_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TickRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetrySampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_synthetic_sample_batch_sources_synthetic_missions__mission_id__samples_get: {
        parameters: {
            query?: {
                count?: number;
                delta_sec?: number | null;
            };
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetrySampleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_sources_snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotListItemResponse"][];
                };
            };
        };
    };
    create_snapshot_sources_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_status_sources_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_samples_sources_snapshots__snapshot_id__samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotSamplesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_snapshot_once_udp_sources_snapshots__snapshot_id__send_once_udp_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UdpStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotSendOnceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_external_sources_sources_external_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalSourceListItemResponse"][];
                };
            };
        };
    };
    create_external_source_sources_external_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalSourceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalSourceCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_external_source_status_sources_external__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalSourceStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_external_source_sources_external__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalSourceDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_external_source_sources_external__source_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalSourceStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_external_source_sources_external__source_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalSourceStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stream_capabilities_streams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    start_synthetic_udp_stream_streams_synthetic_missions__mission_id__udp_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UdpStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdpStreamStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_udp_streams_streams_udp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdpStreamStatusResponse"][];
                };
            };
        };
    };
    get_udp_stream_status_streams_udp__stream_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdpStreamStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_udp_stream_streams_udp__stream_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UdpStreamStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_udp_stream_preview_streams_udp__stream_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_snapshot_udp_stream_streams_snapshots__snapshot_id__udp_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UdpStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotUdpStreamStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshot_udp_streams_streams_snapshots_udp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotUdpStreamStatusResponse"][];
                };
            };
        };
    };
    get_snapshot_udp_stream_status_streams_snapshots_udp__stream_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotUdpStreamStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_snapshot_udp_stream_streams_snapshots_udp__stream_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotUdpStreamStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_udp_stream_preview_streams_snapshots_udp__stream_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translations_translations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationsResponse"];
                };
            };
        };
    };
}
