"""Synthetic anomaly type."""

from enum import StrEnum


class AnomalyType(StrEnum):
    """Supported synthetic anomaly types."""

    GPS_SIGNAL_LOSS = "GPS_SIGNAL_LOSS"
    GPS_SPOOFING = "GPS_SPOOFING"
    IMU_SPIKE = "IMU_SPIKE"
    MOTION_INCONSISTENCY = "MOTION_INCONSISTENCY"
    BATTERY_DROP = "BATTERY_DROP"
    LOW_BATTERY = "LOW_BATTERY"
    TELEMETRY_FREEZE = "TELEMETRY_FREEZE"
    TELEMETRY_GAP = "TELEMETRY_GAP"
    IMPOSSIBLE_ALTITUDE = "IMPOSSIBLE_ALTITUDE"
    ANOMALOUS_BEHAVIOR = "ANOMALOUS_BEHAVIOR"
